Docs: ASP.NET Core WebAPI example(s)
aws-powertools/powertools-lambda-dotnet pull request #287
Opened 2023-06-05 12:25 UTC by swimming-potato

Issue number: [#220](https://github.com/awslabs/aws-lambda-powertools-dotnet/issues/220)

## Summary

### Changes

Introduce an example for ASP.Net WebAPI deployed on AWS Lambda.

### User experience

This is a change in documentation. A section `ServerlessAPi` has been added to the examples. The section demonstrates to AWS Lambda Powertools users: how to leverage logging, metrics and tracing provided by AWS Lambda Powertools in the WebAPI hosted by Kestrel. It contains the code and README.md file to walkthrough the changes. 

## Checklist

Please leave checklist items unchecked if they do not apply to your change.

* [x] [Meets tenets criteria](https://awslabs.github.io/aws-lambda-powertools-dotnet/tenets)
* [ ] I have performed a self-review of this change
* [x] Changes have been tested
* [x] Changes are documented
* [x] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-dotnet/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change?</summary>
No
**RFC issue number**:

Checklist:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

2023-06-09 08:46 UTC, hjgraca approved these changes

2023-06-12 14:01 UTC, amirkaws commented
Unit test is breaking because the FunctionVersion is null
<img width="856" alt="2023-06-12_08-37-24" src="https://github.com/awslabs/aws-lambda-powertools-dotnet/assets/84795239/0b3c23da-e84f-44b2-8ad0-2703fb96766a">

to solve that we can set the 
![2023-06-12_15-00-16](https://github.com/awslabs/aws-lambda-powertools-dotnet/assets/84795239/f4da7799-f3bc-4ecd-910f-a90bd4fe2fb1)

Amazon Copyright comments are missing from files
![2023-06-12_14-58-15](https://github.com/awslabs/aws-lambda-powertools-dotnet/assets/84795239/a32acd8e-10df-4f50-af33-72c63d6ce28f)

2023-06-15 07:51 UTC, swimming-potato commented
HI @amirkaws I did address your comment:) please check the PR.

2023-06-19 08:20 UTC, amirkaws commented
Hi @swimming-potato, thank you a lot for that. I think we are still missing copyright comments, we should add Amazon copyright comment on top of each .cs file. 

![2023-06-12_14-58-15](https://github.com/aws-powertools/powertools-lambda-dotnet/assets/84795239/b10ca2c3-a4fe-4abf-bb5a-c7c674285cd8)


The other thing I believe we should add is a solution file in the example root folder to include both projects juts to be consistent with the. other examples.  here is an example for logging  https://github.com/aws-powertools/powertools-lambda-dotnet/blob/develop/examples/Logging/PowertoolsLoggingExample.sln

2023-06-21 10:21 UTC, hjgraca commented on examples/ServerlessApi/ServerlessApi.sln
Please rename the solution to PowertoolsServerlessApiExample

2023-06-21 10:22 UTC, hjgraca requested changes
Looks good. Small solution name change

2023-06-21 12:22 UTC, hjgraca approved these changes

2023-06-23 09:01 UTC, amirkaws approved these changes
LGTM

2023-06-23 09:07 UTC, hjgraca commented
Thank you for a great work @swimming-potato !

2023-06-23 09:07 UTC, merged