chore(docs): doc and readme updates
aws-powertools/powertools-lambda-dotnet pull request #301
Opened 2023-06-18 15:44 UTC by sliedig

> Please provide the issue number

Issue number:
#285 

## Summary
Updates to docs and readme addressing dotnet cli corrections, updates to idempotency location, link updates to new organisation.

### Changes

> Please provide a summary of what's being changed

### User experience

> Please share what the user experience looks like before and after this change

## Checklist

Please leave checklist items unchecked if they do not apply to your change.

* [x] [Meets tenets criteria](https://docs.powertools.aws.dev/lambda-dotnet/tenets)
* [x] I have performed a self-review of this change
* [x] Changes have been tested
* [x] Changes are documented
* [x] PR title follows [conventional commit semantics](https://github.com/aws-powertools/lambda-dotnet/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change?</summary>

**RFC issue number**:

Checklist:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

2023-06-18 15:45 UTC, sliedig commented on mkdocs.yml
> -      restrict_base_path: false
This is causing local development failures

2023-06-19 11:55 UTC, hjgraca commented on CODEOWNERS
Please remove this file. We will keep the one already present in the .github folder for consistency

2023-06-19 12:01 UTC, hjgraca commented on docs/utilities/idempotency.md
> +	**This utility is currently in developer preview** and is intended strictly for feedback and testing purposes **and not for production workloads**. The version and all future versions tagged with th
Update URL to https://github.com/aws-powertools/powertools-lambda-dotnet/milestone/3

2023-06-19 12:01 UTC, hjgraca commented on docs/we_made_this.md
> +!!! info "[Get your content featured here](https://github.com/aws-powertools/aws-lambda-powertools-dotnet/issues/new?assignees=&labels=community-content&template=share_your_work.yml&title=%5BI+Made+T
Update URL to https://github.com/aws-powertools/powertools-lambda-dotnet/issues/new?assignees=&labels=community-content&template=share_your_work.yml&title=%5BI+Made+This%5D%3A+%3CTITLE%3E

2023-06-19 12:03 UTC, hjgraca requested changes
Delete CODEOWNERS and url changes

2023-06-20 11:44 UTC, hjgraca approved these changes
Pushed changes to @sliedig branch

2023-06-20 14:27 UTC, merged